### ISSUE TITLE
Correction of wrong package structure in a branch named 'pkg-struct-fix'

### ISSUE THREAD

**Issue by furutaka** [kbat/mc-tools#3]
After reading [How To Package Your Python Code](http://python-packaging.readthedocs.org/en/latest/) I think the package structure I made was wrong and tried to correct it in a new branch named 'pkg-struct-fix.

Could you guys test the code in the new branch by installing it e.g. with pip?
(As I use PHITS only, I've only tested angel2root, as always...  Of course I did something like `import mc_tools.common.mixtures`).

**Comment by furutaka** [comment]
I did
```
# pip install git+https://github.com/kbat/mc-tools.git@pkg-struct-fix
```

**Comment by kbat** [comment]
I can test it, but before I do it, can you please confirm that `pip uninstall` really does its work?
Last time, when I tried to install mc-tools using pip, it broke the system and it took me some effort to uninstall the package, so since then I became very cautious.

**Comment by furutaka** [comment]
Well, on my linux boxes, while developing the branch,  I installed and uninstalled using pip for dozens of times without any troubles.  

If you don't want to do it with pip, you can install the branch by
```python setup.py install```
In this case the tool will be installed as an egg file (I don't know how it is controlled, but at least in my case it was installed as an egg), and it can be easily uninstslled by just deleting the egg file.

**Comment by kbat** [comment]
So, I have installed with pip as you suggested and tested some scripts. It seems the scripts I've tested work fine, but pip did not install `mctal2root`.
Uninstall also works fine.
I did everything on Debian. Nicolò, can you please try to do the same on your system?

**Comment by furutaka** [comment]
Well, it has been a bit long since I first structured the tools as a Python package and I do not remember why, but one reason ```mctal2root``` was dropped from 'console_scripts' might be that the script has no ```main()``` function/method or something like that which can be used as its entry point...  Though it may take some time it is not difficult and quite straightforward to modify it; shall I do it?

**Comment by kbat** [comment]
I suggest either I or @NicoloBorghi will do it.

**Comment by kbat** [comment]
I have added the `main()` function for `mctal2root` in the `master` branch.
If you want to apply these changes in `pkg-struct-fix`, you can perform a cherry-pick. I.e., being in your `pkg-struct-fix` branch you have to execute `git cherry-pick 7794c5e`, where `7794c5e` is the hash of my commit. In this case it's the same as copying `mctal2root.py` from man to `pkg-struct-fix`.

BTW, `pip` installs two scripts which are needed only for testing (i.e., they are not supposed to be used by the end-users): `mctaltest` and `roottest`.
Is there a way not to install these scripts with `pip`?

**Comment by furutaka** [comment]
In the `pkg-struct-fix` branch:
1. `mctaltest` and `roottest` were removed from `console_scripts` (bb31679f64af294c695cdb342f9bcf69d45ab67d),
2. then cherry-picked 7794c5e8b9e9a3bcc489740611a90da995de8d3e, and
3. finally `mctal2root` was added to `console_scripts` (b089b14968c1ca08a9dac3587581585f134bca10).

**Comment by kbat** [comment]
thank you!

**Comment by furutaka** [comment]
Would you mind its merge with master?

**Comment by kbat** [comment]
Yes, please do it.

**Comment by furutaka** [comment]
Merged.
